project_id = "lbwnplgambxrwkswftoc"

[functions.analyze-document]
verify_jwt = false

[functions.tax-assistant]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.get-paddle-price]
verify_jwt = false

